spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/fr_database
    password: password
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
