create table poll
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    time_end    timestamp,
    time_start  timestamp,
    title       varchar(255)
);

alter table poll
    owner to postgres;

create table question
(
    id      bigint generated by default as identity
        primary key,
    title   varchar(255),
    type    varchar(255),
    poll_id bigint
        constraint fks9uu0i9ipek2tnqty4ohdek27
            references poll
);

alter table question
    owner to postgres;

create table answer
(
    id          bigint generated by default as identity
        primary key,
    title       varchar(255),
    question_id bigint
        constraint fk8frr4bcabmmeyyu60qt7iiblo
            references question
);

alter table answer
    owner to postgres;

create table users
(
    user_id bigint not null
        primary key
);

alter table users
    owner to postgres;

create table user_response
(
    id           bigint generated by default as identity
        primary key,
    create_date  timestamp,
    poll_id      bigint
        constraint fk9fd9b6ftpyfqna0qbf1indhwn
            references poll,
    user_user_id bigint
        constraint fkph7un18wkkg8qxuhak9uupelh
            references users
);

alter table user_response
    owner to postgres;

create table user_answer
(
    id               bigint generated by default as identity
        primary key,
    answer_text      varchar(255),
    answer_id        bigint
        constraint fkm321eamc0drwpxfkvyl9giypt
            references answer,
    user_response_id bigint
        constraint fk1593waipp2em0tx4xrtaf3l94
            references user_response
);

alter table user_answer
    owner to postgres;

